name: Flowzone

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches: [main, master]
  push:
    tags:
      - '*.*.*'
    branches: [main, master]

jobs:
  flowzone:
    name: Flowzone
    uses: product-os/flowzone/.github/workflows/flowzone.yml@866cb343f30483b8bbf15ba0ce30727f81d93062 # v23.0.20
    secrets:
      GH_APP_PRIVATE_KEY: ${{ secrets.GH_APP_PRIVATE_KEY }}
      DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      disable_versioning: true
      toggle_auto_merge: false
      docker_images: |
        ghcr.io/klutchell/dnscrypt-proxy,
        docker.io/klutchell/dnscrypt-proxy
